### PR TITLE
pass through sessionId, serverURL, and apiVersion in all sf: ant calls

### PR DESCRIPTION
**Pull request by cdcarter**
review with w=1 ;)

### CODE REVIEW

**Comment by cdcarter** [comment]
note: in order to use a sf.sessionId attribute, you do need to make sure sf.username and sf.password are blank (NOT unassigned)

**Comment by jlantz** [comment]
Would it make sense to add an environment variable mapping like SF_USERNAME and SF_PASSWORD and potentially override SF_USERNAME and SF_PASSWORD to force them to be a blank string if the sessionId is available around here:

https://github.com/SalesforceFoundation/CumulusCI/blob/master/build/build.xml#L45

**Comment by cdcarter** [comment]
Like that? :)

**Comment by jlantz** [comment]
Perfect :)

**Pull request merged**
